name: test
on:
  pull_request:
  push:
    branches:
      - "main"
defaults:
  run:
    shell: sh
env:
  go-version: 1.17
  cache-version: 1
jobs:
  validation:
    name: Validation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
