name: iftest
on:
  pull_request:
  push:
    branches:
      - "main"
      - "stage"
      - "release"
defaults:
  run:
    shell: sh
env:
  go-version: 1.17
  cache-version: 1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "test"
  upgrade:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref != 'refs/heads/stage' || github.ref != 'refs/head/release' || !startsWith(github.ref, 'refs/head/op-stage') || !startsWith(github.ref, 'refs/head/op-release')
    steps:
      - uses: actions/checkout@v3
      - run: echo "upgrade"

