name: release
on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          gh release create ${TAG_NAME} hoge.txt README.md
