name: release
on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          gh release create ${TAG_NAME} \
            --title "Release ${TAG_NAME}" \
            --notes "See [CHANGELOG.md](./CHANGELOG.md) for details." \
            --notes "add notes" \
            --generate-notes \
            hoge.txt README.md
